# Generated by Django 3.0.4 on 2020-03-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('locale_code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('unicode_range', models.CharField(max_length=20)),
                ('unicode_chart', models.CharField(max_length=50)),
                ('font_used', models.CharField(max_length=50)),
                ('rendering_engine_used', models.CharField(choices=[('pango', 'pango'), ('harfbuz', 'harfbuzz'), ('other', 'other')], default='pango', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utrrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_data_type', models.CharField(choices=[('codepoint', 'codepoint'), ('gsub', 'gsub'), ('gpos', 'gpos')], default='codepoint', max_length=20)),
                ('image', models.ImageField(upload_to='reference_images')),
                ('rawcode', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('locale_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utrrsApp.Lang')),
            ],
        ),
    ]
